# Piece-square tables and material values, combined into single lookup tables
# indexed by piece code and square. Values are centipawns, positive = good for
# white. Tables are generated programmatically at startup (deterministic);
# they serve as the initial evaluation and a Texel-tuning baseline.
#
# Convention inside make(): adding a WHITE piece adds its value, adding a
# BLACK piece subtracts it, so mgv/egv accumulate as (white - black).

module Experion
  module Psqt
    extend self

    MATERIAL_MG = StaticArray[82, 337, 365, 477, 1025, 0]
    MATERIAL_EG = StaticArray[94, 281, 297, 512, 936, 0]

    # phase increments: N/B = 1, R = 2, Q = 4 (total 24)
    PHASE_INC = StaticArray[0, 1, 1, 2, 4, 0]

    CENTER_D = StaticArray[3, 2, 1, 0, 0, 1, 2, 3]

    MG_PAWN_RANK = StaticArray[0, -12, -4, 8, 20, 42, 80, 0]   # by relative rank
    EG_PAWN_RANK = StaticArray[0, 8, 12, 22, 44, 84, 150, 0]

    TABLE_MG = StaticArray(Int32, 768).new(0)
    TABLE_EG = StaticArray(Int32, 768).new(0)

    private def cdist(f : Int, r : Int) : Int32
      CENTER_D[f] + CENTER_D[r]
    end

    # base PST for white piece of given type at (file, relative rank)
    private def pst_mg(ptype : Int, f : Int, rr : Int) : Int32
      case ptype
      when PAWN
        v = MG_PAWN_RANK[rr]
        v += 8 if f.in?(2..5)
        v -= 6 if f.in?(0, 7)
        v
      when KNIGHT
        -(cdist(f, rr) * 5) + 10
      when BISHOP
        -(cdist(f, rr) * 3) + 5
      when ROOK
        v = 0
        v += 24 if rr == 6          # seventh rank
        v -= CENTER_D[f] * 2        # prefer flank files slightly
        v
      when QUEEN
        -(cdist(f, rr) * 1)
      when KING
        v = 10
        v -= rr * 14                # stay on the back rank in the middlegame
        v -= CENTER_D[f] * 6
        v
      else
        0
      end
    end

    private def pst_eg(ptype : Int, f : Int, rr : Int) : Int32
      case ptype
      when PAWN
        EG_PAWN_RANK[rr] + (f.in?(2..5) ? 6 : 0)
      when KNIGHT
        -(cdist(f, rr) * 4)
      when BISHOP
        -(cdist(f, rr) * 3)
      when ROOK
        -(CENTER_D[f] * 4) - (CENTER_D[rr] * 2)
      when QUEEN
        -(cdist(f, rr) * 4)
      when KING
        -(cdist(f, rr) * 11)
      else
        0
      end
    end

    def init : Nil
      pc = 0
      while pc < 12
        color = pc // 6
        ptype = pc % 6
        sq = 0
        while sq < 64
          f = sq & 7
          r = sq >> 3
          # relative rank: white sees rank 1 as its first rank
          rr = color == WHITE ? r : 7 - r
          fr = color == WHITE ? f : 7 - f
          v_mg = MATERIAL_MG[ptype] + pst_mg(ptype, fr, rr)
          v_eg = MATERIAL_EG[ptype] + pst_eg(ptype, fr, rr)
          if color == BLACK
            v_mg = -v_mg
            v_eg = -v_eg
          end
          TABLE_MG[(pc << 6) + sq] = v_mg
          TABLE_EG[(pc << 6) + sq] = v_eg
          sq += 1
        end
        pc += 1
      end

      # overlay tuned tables when present (generated by tools/texel_tune.cr)
      PsqtTuned.init
    end

    def apply_tuned : Nil
      PsqtTuned.init
    end

    @[AlwaysInline]
    def mg(pc : Int, sq : Int) : Int32
      # to_i! guards against UInt8 args: small-int shifts would wrap
      TABLE_MG.unsafe_fetch((pc.to_i! << 6) + sq)
    end

    @[AlwaysInline]
    def eg(pc : Int, sq : Int) : Int32
      TABLE_EG.unsafe_fetch((pc.to_i! << 6) + sq)
    end

    @[AlwaysInline]
    def phase_of(pc : Int) : Int32
      PHASE_INC.unsafe_fetch(pc % 6)
    end
  end
end
