# Codegen: finds fancy-magic constants and emits them as a Crystal source file
# so the engine binary needs no magic search at startup.
#
#   crystal run tools/gen_magics.cr --release
#
# Writes src/experion/magic_constants.cr (checked in).

require "../src/experion/types"
require "../src/experion/tables"
require "../src/experion/move"
require "../src/experion/psqt"
require "../src/experion/position"

module Experion
  module GenMagics
    extend self

    DIRS_ROOK    = [{1, 0}, {-1, 0}, {0, 1}, {0, -1}]
    DIRS_BISHOP  = [{1, 1}, {1, -1}, {-1, 1}, {-1, -1}]

    private def slider_mask(sq : Int, is_rook : Bool) : UInt64
      f = sq & 7
      r = sq >> 3
      m = 0u64
      if is_rook
        (f + 1...7).each { |x| m |= 1u64 << (r * 8 + x) }
        (1...f).each { |x| m |= 1u64 << (r * 8 + x) }
        (r + 1...7).each { |y| m |= 1u64 << (y * 8 + f) }
        (1...r).each { |y| m |= 1u64 << (y * 8 + f) }
      else
        DIRS_BISHOP.each do |df, dr|
          x_f = f + df
          x_r = r + dr
          while x_f.in?(1..6) && x_r.in?(1..6)
            m |= 1u64 << (x_r * 8 + x_f)
            x_f += df
            x_r += dr
          end
        end
      end
      m
    end

    private struct Prng
      def initialize(state : UInt64)
        @state = state.zero? ? 0xDEADBEEFu64 : state
      end

      def next : UInt64
        x = @state
        x = x ^ (x >> 12)
        x = x ^ (x << 25)
        x = x ^ (x >> 27)
        @state = x
        x &* 0x2545F4914F6CDD1Du64
      end
    end

    record Result, magics : StaticArray(UInt64, 64)

    private def find_magics_impl(is_rook : Bool) : Result
      dirs = is_rook ? DIRS_ROOK : DIRS_BISHOP
      salt = is_rook ? 0xBF58476D1CE4E5B9u64 : 0x94D049BB133111EBu64
      magics = StaticArray(UInt64, 64).new(0u64)

      sq = 0
      while sq < 64
        mask = slider_mask(sq, is_rook)
        bits = mask.popcount

        n = 1 << bits
        subsets = Array(UInt64).new(n)
        refs = Array(UInt64).new(n)
        s = 0u64
        loop do
          subsets << s
          refs << slow_attacks(sq, s, dirs)
          s = (s &- mask) & mask
          break if s.zero?
        end

        rng = Prng.new(0x9E3779B97F4A7C15u64 ^ (sq.to_u64 &* salt))
        taken = Array(Bool).new(n, false)
        seen = Array(UInt64).new(n, 0u64)
        magic = 0u64
        found = false
        until found
          candidate = rng.next & rng.next & rng.next
          next unless ((candidate &* mask) >> 57).popcount >= 6

          taken.fill(false)
          ok = true
          i = 0
          while i < n
            idx = (subsets.unsafe_fetch(i) &* candidate) >> (64 - bits)
            if taken.unsafe_fetch(idx)
              # aliasing is fine only if both subsets produce identical attacks
              unless seen.unsafe_fetch(idx) == refs.unsafe_fetch(i)
                ok = false
                break
              end
            else
              taken[idx] = true
              seen[idx] = refs.unsafe_fetch(i)
            end
            i += 1
          end
          if ok
            magic = candidate
            found = true
          end
        end

        magics[sq] = magic
        sq += 1
      end
      Result.new(magics)
    end

    private def slow_attacks(sq : Int, occ : UInt64, dirs) : UInt64
      f = sq & 7
      r = sq >> 3
      result = 0u64
      dirs.each do |df, dr|
        x_f = f + df
        x_r = r + dr
        while x_f.in?(0..7) && x_r.in?(0..7)
          s = x_r * 8 + x_f
          result |= 1u64 << s
          break if ((occ >> s) & 1) != 0
          x_f += df
          x_r += dr
        end
      end
      result
    end

    def self.emit : Nil
      t0 = Time.instant
      rooks = find_magics_impl(true)
      bishops = find_magics_impl(false)
      puts "found magics in #{(Time.instant - t0).total_milliseconds}ms"

      File.open("src/experion/magic_constants.cr", "w") do |f|
        f.puts "# GENERATED by tools/gen_magics.cr — do not edit by hand."
        f.puts "# Fancy-magic multipliers per square (deterministic seed)."
        f.puts "module Experion"
        f.puts "  module MagicConstants"
        f.print "    ROOK_MAGICS = StaticArray["
        64.times do |sq|
          f.print "#{rooks.magics[sq]}u64, "
        end
        f.puts "]"
        f.print "    BISHOP_MAGICS = StaticArray["
        64.times do |sq|
          f.print "#{bishops.magics[sq]}u64, "
        end
        f.puts "]"
        f.puts "  end"
        f.puts "end"
      end
      puts "wrote src/experion/magic_constants.cr"
    end
  end
end

Experion::GenMagics.emit
