# Texel-style PSQT tuner.
#
#   experion gendata <games> <ms> training.txt     # produce data first
#   crystal run tools/texel_tune.cr --release -- training.txt
#
# Fits Psqt::TABLE_MG / TABLE_EG to game results via logistic loss +
# SGD. Emits src/experion/psqt_tuned.cr (checked in) whose init() overwrites
# the programmatic tables with tuned values.

require "../src/experion"

module Experion
  module Tune
    extend self
    struct Sample
      getter pairs : Array(UInt16) # packed pc<<6 | sq for each occupied square
      getter phase : Int32
      getter stm_white : Bool
      getter result : Float64

      def initialize(@pairs : Array(UInt16), @phase : Int32, @stm_white : Bool, @result : Float64); end
    end

    @@table_mg : Pointer(Int32)? = nil
    @@table_eg : Pointer(Int32)? = nil

    def self.load(path : String) : Array(Sample)
      samples = Array(Sample).new(100_000)
      File.each_line(path) do |line|
        semi = line.index(';')
        next unless semi
        fen = line[0...semi]
        res = line[(semi + 1)..].to_f? || 0.5
        begin
          pos = Position.new(fen)
        rescue
          next
        end
        pairs = Array(UInt16).new(32)
        sq = 0
        while sq < 64
          pc = pos.piece_at(sq)
          pairs << (pc.to_i << 6 | sq).to_u16! unless pc == NO_PIECE
          sq += 1
        end
        samples << Sample.new(pairs, pos.phase.clamp(0, 24), pos.stm == WHITE.to_u8!, res)
      end
      samples
    end

    @[AlwaysInline]
    private def tapered(s : Sample, mgp : Pointer(Float64), egp : Pointer(Float64)) : Float64
      mg = 0.0
      eg = 0.0
      s.pairs.each do |pk|
        idx = pk.to_i!
        mg += mgp[idx]
        eg += egp[idx]
      end
      ph = s.phase.to_f
      sc = (mg * ph + eg * (24.0 - ph)) / 24.0
      sc += s.stm_white ? Eval::TEMPO : -Eval::TEMPO
      s.stm_white ? sc : -sc
    end

    def self.run(path : String, epochs : Int32, lr : Float64, k : Float64) : Nil
      Tables.init
      Zobrist.init
      Psqt.init

      puts "loading..."
      all = load(path)
      abort "no samples" if all.empty?
      all.shuffle!(Random.new(42))
      holdout = all.size // 20
      val = all[0...holdout]
      train = all[holdout..]
      puts "#{train.size} train / #{val.size} validation"

      mgp = Pointer(Float64).malloc(768)
      egp = Pointer(Float64).malloc(768)
      i = 0
      while i < 768
        mgp[i] = Psqt::TABLE_MG.unsafe_fetch(i).to_f
        egp[i] = Psqt::TABLE_EG.unsafe_fetch(i).to_f
        i += 1
      end

      gmg = Pointer(Float64).malloc(768)
      geg = Pointer(Float64).malloc(768)

      eval_loss = ->(set : Array(Sample)) : Float64 do
        tot = 0.0
        set.each do |s|
          e = tapered(s, mgp, egp) / 100.0
          sig = 1.0 / (1.0 + Math.exp(-k * e))
          d = s.result - sig
          tot += d * d
        end
        tot / set.size
      end

      best_val = eval_loss.call(val)
      puts "initial: train=#{eval_loss.call(train).round(5)} val=#{best_val.round(5)}"

      cur_lr = lr
      epoch = 0
      while epoch < epochs
        train.shuffle!(Random.new(epoch + 1))
        train.each do |s|
          e = tapered(s, mgp, egp) / 100.0
          sig = 1.0 / (1.0 + Math.exp(-k * e))
          err = sig - s.result
          # dL/dscore = 2*err*k*sig*(1-sig); chain through taper weights
          base = 2.0 * err * k * sig * (1.0 - sig) / 100.0
          wmg = base * s.phase.to_f / 24.0
          weg = base * (24 - s.phase).to_f / 24.0
          sign = s.stm_white ? 1 : -1
          s.pairs.each do |pk|
            idx = pk.to_i!
            gmg[idx] += wmg * sign
            geg[idx] += weg * sign
          end
        end
        # entries are stored signed (black negated); gradients are averaged
        # over the epoch so the learning rate stays meaningful at any size
        n_inv = 1.0 / train.size.to_f
        i = 0
        while i < 768
          mgp[i] -= cur_lr * gmg[i] * n_inv
          egp[i] -= cur_lr * geg[i] * n_inv
          gmg[i] = 0.0
          geg[i] = 0.0
          i += 1
        end

        if (epoch + 1) % 5 == 0 || epoch == epochs - 1
          vl = eval_loss.call(val)
          puts "epoch #{epoch + 1}: lr=#{cur_lr.round(5)} train=#{eval_loss.call(train).round(5)} val=#{vl.round(5)}"
          if vl < best_val
            best_val = vl
            emit(mgp, egp)
          end
          cur_lr *= 0.85
        end
        epoch += 1
      end
      puts "best validation loss: #{best_val.round(5)} (src/experion/psqt_tuned.cr written)"
    end

    private def self.emit(mgp : Pointer(Float64), egp : Pointer(Float64)) : Nil
      File.open("src/experion/psqt_tuned.cr", "w") do |f|
        f.puts "# GENERATED by tools/texel_tune.cr — tuned piece-square tables."
        f.puts "module Experion"
        f.puts "  module PsqtTuned"
        f.puts "    MG = StaticArray(Int32, 768).new(0)"
        f.puts "    EG = StaticArray(Int32, 768).new(0)"
        f.puts ""
        f.puts "    def self.init : Nil"
        f.print "      ["
        i = 0
        while i < 768
          f.print "," if i > 0
          f.print mgp[i].round.to_i
          i += 1
        end
        f.puts "].each_with_index { |v, j| MG[j] = v }"
        f.print "      ["
        i = 0
        while i < 768
          f.print "," if i > 0
          f.print egp[i].round.to_i
          i += 1
        end
        f.puts "].each_with_index { |v, j| EG[j] = v }"
        f.puts "    end"
        f.puts "  end"
        f.puts "end"
      end
    end
  end
end

path = ARGV[0]? || "training.txt"
epochs = ARGV[1]?.try(&.to_i?) || 60
lr = ARGV[2]?.try(&.to_f?) || 1500.0
k = ARGV[3]?.try(&.to_f?) || 1.13
Experion::Tune.run(path, epochs, lr, k)
